import type { Metadata } from "next";
import { Boldonse, Geist, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const boldonse = Boldonse({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-boldonse",
  adjustFontFallback: false,
});

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist",
});

export const metadata: Metadata = {
  title: "Govern",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        boldonse.variable,
        geist.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full w-full flex flex-col">{children}</body>
    </html>
  );
}
